In [1]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3]);
print("1D:",arr1)
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D:",arr2)
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [9,8,7]
    ]
])
print("3D:",arr3)

1D: [1 2 3]
2D: [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D: [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]]


In [6]:
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)
print(arr3.dtype)

(2, 2, 3)
3
12
int64


In [15]:
A = np.arange(9).reshape(3,3)
B = np.random.random(9).reshape(3,3)
print("A:",A)
print("B:",B)
print("A+B:",A+B)
print("A-B:",A-B)
print("A*B:",A*B)
print("A/B:",A/B)

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]
B: [[0.48842858 0.70419284 0.79899973]
 [0.6418924  0.16893077 0.1796993 ]
 [0.68302354 0.90549297 0.64220233]]
A+B: [[0.48842858 1.70419284 2.79899973]
 [3.6418924  4.16893077 5.1796993 ]
 [6.68302354 7.90549297 8.64220233]]
A-B: [[-0.48842858  0.29580716  1.20100027]
 [ 2.3581076   3.83106923  4.8203007 ]
 [ 5.31697646  6.09450703  7.35779767]]
A*B: [[0.         0.70419284 1.59799946]
 [1.92567719 0.6757231  0.8984965 ]
 [4.09814124 6.33845077 5.13761864]]
A/B: [[ 0.          1.42006556  2.50312976]
 [ 4.67368055 23.6783381  27.8242596 ]
 [ 8.78447029  7.73059565 12.45713324]]


In [16]:
print("Tranpose:",A.T);

Tranpose: [[0 3 6]
 [1 4 7]
 [2 5 8]]


In [19]:
#Accessing element's
print(A[0,1])
print(A[:,1])
print(A[1,:])

1
[1 4 7]
[3 4 5]


In [22]:
#Basic matrix operations
print("A:",A);
print("A's sum:",A.sum())
print("A's mean:",A.mean())
print("A's min:",A.min())
print("A's max:",A.max())
print("A's sum column wise:",A.sum(axis=0))
print("A's sum row wise:",A.sum(axis=1))


A: [[0 1 2]
 [3 4 5]
 [6 7 8]]
A's sum: 36
A's mean: 4.0
A's min: 0
A's max: 8
A's sum column wise: [ 9 12 15]
A's sum row wise: [ 3 12 21]


In [26]:
C = np.random.rand(2,3)
print(C) #randome values (they will change on each run)

[[0.6568611  0.92742856 0.74963046]
 [0.89173186 0.95992451 0.3878634 ]]


In [30]:
np.random.seed(42); #fix the random pattern
print(np.random.rand(2,4,3));

[[[0.37454012 0.95071431 0.73199394]
  [0.59865848 0.15601864 0.15599452]
  [0.05808361 0.86617615 0.60111501]
  [0.70807258 0.02058449 0.96990985]]

 [[0.83244264 0.21233911 0.18182497]
  [0.18340451 0.30424224 0.52475643]
  [0.43194502 0.29122914 0.61185289]
  [0.13949386 0.29214465 0.36636184]]]


In [35]:
arr4=np.arange(1,17).reshape(4,4);
arr5=np.arange(1,17).reshape(2,8);
print("arr4:",arr4,"arr4 T:",arr4.T);
print("arr5:",arr5,"arr5 T:",arr5.T);
flat1 = arr4.flatten()
print("arr4:",flat1);
print("arr4:",arr4.ravel())
print("arr4 Transpose:",flat1.T);
print("Sum:", arr4.sum())
print("Mean:", arr4.mean())
print("Standard Deviation:", arr4.std())


arr4: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] arr4 T: [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
arr5: [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]] arr5 T: [[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]
 [ 8 16]]
arr4: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
arr4: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
arr4 Transpose: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Sum: 136
Mean: 8.5
Standard Deviation: 4.6097722286464435


In [41]:
arr3d = np.arange(1,25).reshape(2,3,4)
print('Arr3d:',arr3d);
print("Shape:",arr3d.shape)
print("Dimension:",arr3d.ndim)
print(arr3d[1])
print(arr3d[0,1])
print(arr3d[0,1,3])

Arr3d: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Dimension: 3
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[5 6 7 8]
8


In [44]:
print("Arr3d to Arr1d:",arr3d.flatten())

Arr3d to Arr1d: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
