In [1]:
import numpy as np;

In [2]:
arr = np.array([1,5,2,8,6]);
print(arr);

[1 5 2 8 6]


In [3]:
print("mean:",np.mean(arr));
print("median:",np.mean(arr));
print("mean:",np.mean(arr));
print("mean:",np.mean(arr));
print("mean:",np.mean(arr));

mean: 4.4
median: 4.4
mean: 4.4
mean: 4.4
mean: 4.4


In [6]:
for i in enumerate(arr):
    print(i);

(0, np.int64(1))
(1, np.int64(5))
(2, np.int64(2))
(3, np.int64(8))
(4, np.int64(6))


In [4]:
rows=int(input("Enter rows:"));
cols=int(input("Enter cols:"));
arr2d = np.zeros((rows,cols),dtype=int);
print(arr2d)

Enter rows: 4
Enter cols: 4


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
for i in range(rows):
    for j in range(cols):
        arr2d[i][j]=int(input("Enter value:"));
print(arr2d)

Enter value: 2
Enter value: 2
Enter value: 1
Enter value: 2
Enter value: 3
Enter value: 4
Enter value: 5
Enter value: 6
Enter value: 7
Enter value: 8
Enter value: 78
Enter value: 88
Enter value: 8
Enter value: 8
Enter value: 8
Enter value: 8


[[ 2  2  1  2]
 [ 3  4  5  6]
 [ 7  8 78 88]
 [ 8  8  8  8]]


In [13]:
arr3d = np.arange(16).reshape(2,2,4);
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [15]:
print(f"printing array shape {arr3d.shape}")
print(f"array first page {arr3d[0]}")
print(f"printing first page's first row {arr3d[0][0]}")
print(f"printing first page's first row's first element {arr3d[0][0][0]}")


printing array shape (2, 2, 4)
array first page [[0 1 2 3]
 [4 5 6 7]]
printing first page's first row [0 1 2 3]
printing first page's first row's first element 0


In [16]:
import pandas as pd;

In [17]:
print(pd.__version__)

2.2.3


In [18]:
data={
    "Name":["Imran","Aslam","Hasan","Irfan"],
    "Age":[22,23,21,24],
    "Salary":[20000,22000,23000,21000]
}
print(data);

{'Name': ['Imran', 'Aslam', 'Hasan', 'Irfan'], 'Age': [22, 23, 21, 24], 'Salary': [20000, 22000, 23000, 21000]}


In [19]:
df=pd.DataFrame(data);
print(df)

    Name  Age  Salary
0  Imran   22   20000
1  Aslam   23   22000
2  Hasan   21   23000
3  Irfan   24   21000


In [24]:
print(df["Name"])
print(df[["Age","Salary"]]);

0    Imran
1    Aslam
2    Hasan
3    Irfan
Name: Name, dtype: object
   Age  Salary
0   22   20000
1   23   22000
2   21   23000
3   24   21000


In [30]:
print(df.loc[0,"Name"]);
print(df.iloc[0,1]);
print(df.iloc[1]);
print(df.loc[0]);

Imran
22
Name      Aslam
Age          23
Salary    22000
Name: 1, dtype: object
Name      Imran
Age          22
Salary    20000
Name: 0, dtype: object


In [31]:
print(f"shape:{df.shape}");
print(f"columns:{df.columns}");
print(f"Data types of each column:{df.dtypes}");

shape:(4, 3)
columns:Index(['Name', 'Age', 'Salary'], dtype='object')
Data types of each column:Name      object
Age        int64
Salary     int64
dtype: object


In [34]:
print("Detailed info:",df.describe())

Detailed info:              Age        Salary
count   4.000000      4.000000
mean   22.500000  21500.000000
std     1.290994   1290.994449
min    21.000000  20000.000000
25%    21.750000  20750.000000
50%    22.500000  21500.000000
75%    23.250000  22250.000000
max    24.000000  23000.000000


In [38]:
df["Bonus"] = df["Salary"] * 0.1;
print(df)

    Name  Age  Salary   Bonus
0  Imran   22   20000  2000.0
1  Aslam   23   22000  2200.0
2  Hasan   21   23000  2300.0
3  Irfan   24   21000  2100.0


In [39]:
print(df.drop("Bonus",axis=1));

    Name  Age  Salary
0  Imran   22   20000
1  Aslam   23   22000
2  Hasan   21   23000
3  Irfan   24   21000


In [45]:
n_row={
    "Name":"Eve",
    "Age":32,
    "Salary":26
}

# df = df.append(n_row,ignore_index=True); #depreciated
print(pd.DataFrame([n_row]));
df = pd.concat([df,pd.DataFrame([n_row])],ignore_index=True);
print(df);

  Name  Age  Salary
0  Eve   32      26
    Name  Age  Salary   Bonus
0  Imran   22   20000  2000.0
1  Aslam   23   22000  2200.0
2  Hasan   21   23000  2300.0
3  Irfan   24   21000  2100.0
4    Eve   32      26     NaN
5    Eve   32      26     NaN
6    Eve   32      26     NaN


In [44]:
print(df.drop([4,3]));

    Name  Age  Salary   Bonus
0  Imran   22   20000  2000.0
1  Aslam   23   22000  2200.0
2  Hasan   21   23000  2300.0
5    Eve   32      26     NaN


In [46]:
print(df.isnull());

    Name    Age  Salary  Bonus
0  False  False   False  False
1  False  False   False  False
2  False  False   False  False
3  False  False   False  False
4  False  False   False   True
5  False  False   False   True
6  False  False   False   True


In [48]:
print(df.isnull().sum())

Name      0
Age       0
Salary    0
Bonus     3
dtype: int64


In [50]:
print("Total Null Values:",df.isnull().sum().sum())

Total Null Values: 3


In [52]:
print(df.fillna(0));

    Name  Age  Salary   Bonus
0  Imran   22   20000  2000.0
1  Aslam   23   22000  2200.0
2  Hasan   21   23000  2300.0
3  Irfan   24   21000  2100.0
4    Eve   32      26     0.0
5    Eve   32      26     0.0
6    Eve   32      26     0.0


In [54]:
print(df.fillna(df.select_dtypes(include='number').mean()))

    Name  Age  Salary   Bonus
0  Imran   22   20000  2000.0
1  Aslam   23   22000  2200.0
2  Hasan   21   23000  2300.0
3  Irfan   24   21000  2100.0
4    Eve   32      26  2150.0
5    Eve   32      26  2150.0
6    Eve   32      26  2150.0
